language: node_js
node_js:
  - "0.12"
  - "4.2"
  - "4.3"
  - "5.5"
  - "5.6"
  - "5.7"

before_script:
  - npm install -g coveralls
  - npm install -g codacy-coverage

script:
  - npm run test-cov

after_script:
  - cat ./coverage/lcov.info | coveralls
  - cat ./coverage/lcov.info | codacy-coverage