language: node_js
node_js:
  - "6"
  - "7"

cache:
  directories:
  - node_modules

before_script:
  - npm install -g coveralls

script:
  - npm run test:coverage

after_success:
  - nyc report --reporter=text-lcov | coveralls
