language: node_js
node_js:
  - "4.9"
  - "5.12"
  - "6.14"
  - "8.11"
  - "9.11"
  - "10.6"

before_script:
  - npm install -g coveralls
  - npm install -g codacy-coverage

script:
  - npm run test-cov

after_script:
  - cat ./coverage/lcov.info | coveralls
  - cat ./coverage/lcov.info | codacy-coverage