environment:
  matrix:
  - nodejs_version: "4.9"
  - nodejs_version: "5.12"
  - nodejs_version: "6.14"
  - nodejs_version: "8.11"
  - nodejs_version: "9.11"
  - nodejs_version: "10.6"
platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install

test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
build: off