environment:
  matrix:
  - nodejs_version: "4.2"
  - nodejs_version: "4.3"
  - nodejs_version: "5.5"
  - nodejs_version: "5.6"
  - nodejs_version: "5.7"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
build: off